# Generated by Django 2.2.12 on 2020-11-17 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('birthday', models.DateField(verbose_name='Birthdate')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'AuthorS',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('text', models.TextField(default='', verbose_name='Text')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('tags', models.CharField(max_length=1024, verbose_name='Tags')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'QuestionS',
            },
        ),
    ]
